[project]
name = "open-router"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "load-dotenv>=0.1.0",
    "openai-agents[litellm]>=0.0.13",
    "python-dotenv>=1.1.0",
    "ruff>=0.11.7",
]
