[project]
name = "mcp_sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.12.3",
    "openai-agents>=0.2.5",
    "requests>=2.32.4",
    "rich>=14.1.0",
]
